# Generated by Django 3.2.3 on 2023-12-19 18:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='country_of_birth',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
