# Generated by Django 3.2.3 on 2023-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231219_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
