# Generated by Django 3.2.3 on 2023-12-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_author_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock_available',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
