# Generated by Django 3.2.3 on 2023-12-24 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_of_review',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
