# Generated by Django 3.2.3 on 2023-12-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_reviews_date_of_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'reviews'},
        ),
    ]
