# Generated by Django 3.2.3 on 2023-12-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_more_info/'),
        ),
    ]
