# Generated by Django 3.2.3 on 2023-12-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_careers_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
